# These are supported funding model platforms

github: [Igladyshev]
# patreon: # your_patreon_username
# open_collective: # your_open_collective_username
# ko_fi: # your_ko_fi_username
# tidelift: # your_tidelift_package_name
# community_bridge: # your_community_bridge_project_name
# liberapay: # your_liberapay_username
# issuehunt: # your_issuehunt_username
# custom: # your_custom_sponsorship_url
