-- DDL Statements generated by YAML Shredder
-- Dialect: POSTGRES
-- Tables: 3

-- Table: deployments
CREATE TABLE "deployments" (
    "id" INTEGER NOT NULL,
    "deployment_code" VARCHAR(9) NOT NULL,
    "name" VARCHAR(30) NOT NULL,
    "active" BOOLEAN NOT NULL
,
    PRIMARY KEY ("id")
);

-- Table: communities
CREATE TABLE "communities" (
    "id" INTEGER NOT NULL,
    "parent_id" INTEGER NOT NULL,
    "name" VARCHAR(16) NOT NULL,
    "population" INTEGER NOT NULL
,
    PRIMARY KEY ("id")
);
ALTER TABLE "communities" ADD CONSTRAINT "FK_communities_deployments_id" FOREIGN KEY ("parent_id") REFERENCES "deployments"("id");

-- Table: sensor_actions
CREATE TABLE "sensor_actions" (
    "id" INTEGER NOT NULL,
    "parent_id" INTEGER NOT NULL,
    "sensor_type" VARCHAR(16) NOT NULL,
    "threshold" FLOAT NULL,
    "enabled" BOOLEAN NOT NULL
,
    PRIMARY KEY ("id")
);
ALTER TABLE "sensor_actions" ADD CONSTRAINT "FK_sensor_actions_deployments_id" FOREIGN KEY ("parent_id") REFERENCES "deployments"("id");

