{% set name = "schema-sentinel" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/schema_sentinel-{{ version }}.tar.gz
  # sha256 will be added after PyPI upload

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - schema-sentinel = schema_sentinel.cli:main

requirements:
  host:
    - python >=3.13,<3.14
    - pip
    - hatchling
  run:
    - python >=3.13,<3.14
    - click >=8.1.3
    - pandas >=2.0.1
    - snowflake-connector-python >=3.0.3
    - snowflake-snowpark-python >=1.11.0
    - pydantic >=2.0.0
    - cryptography >=39.0.2
    - snowflake-sqlalchemy >=1.4.7
    - jinja2 >=3.1.2
    - tinyhtml >=1.2.0
    - markdownmaker >=0.4.0
    - tabulate >=0.9.0
    - simple-ddl-parser >=0.30.0
    - snakemd >=2.1.0
    - sql-formatter >=0.6.2
    - sqlparse >=0.4.4
    - pdfkit >=1.0.0
    - alembic >=1.11.3
    - sqlalchemy >=1.4.49,<2.0
    - typer >=0.9.0
    - sqlalchemy-json >=0.7.0
    - python-dotenv >=1.2.1
    - jsonschema >=4.0.0
    - genson >=1.2.2

test:
  imports:
    - schema_sentinel
    - yaml_shredder
  commands:
    - schema-sentinel --help

about:
  home: https://github.com/Igladyshev/schema-sentinel
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Data processing toolkit for YAML/JSON to relational tables, schema comparison, and metadata management
  description: |
    Schema Sentinel provides powerful tools for transforming nested YAML/JSON data
    into relational structures, generating dynamic schemas, comparing data, and
    tracking database schema changes.
  dev_url: https://github.com/Igladyshev/schema-sentinel

extra:
  recipe-maintainers:
    - Igladyshev
