-- DDL Statements generated by YAML Shredder
-- Dialect: SQLITE
-- Tables: 3

-- Table: MPM_CONFIG
CREATE TABLE "MPM_CONFIG" (
    "deployment_version" TEXT NOT NULL,
    "domain_code" TEXT NOT NULL,
    "internal_stage" TEXT NOT NULL,
    "external_stage" TEXT NOT NULL,
    "domain_timezone" TEXT NOT NULL,
    "generic_reporting_version" TEXT NOT NULL
);

-- Table: COMMUNITIES
CREATE TABLE "COMMUNITIES" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "_row_index" INTEGER NOT NULL
,
    PRIMARY KEY ("id")
);

-- Table: ACTIONS
CREATE TABLE "ACTIONS" (
    "action_type" TEXT NOT NULL,
    "action_code" TEXT NOT NULL,
    "abbreviation" TEXT NOT NULL,
    "communities" TEXT NULL,
    "consumer_tags_AML" TEXT NULL,
    "consumer_tags_Finance" TEXT NULL,
    "consumer_tags_Regulatory" TEXT NULL,
    "date_range_function" TEXT NOT NULL,
    "header_information_header_support" TEXT NULL,
    "header_information_no_header_column" TEXT NULL,
    "parents" TEXT NULL,
    "pii_information_csv_column_encryption" TEXT NULL,
    "pii_information_decrypt_method" TEXT NULL,
    "pii_information_encryption_support" TEXT NULL,
    "query_reference_database_name" TEXT NOT NULL,
    "query_reference_query" TEXT NOT NULL,
    "query_reference_query_version" TEXT NULL,
    "report_file_name_pattern" TEXT NULL,
    "report_name" TEXT NULL,
    "schedule_crontab" TEXT NOT NULL,
    "schedule_timezone" TEXT NOT NULL,
    "start_date" TEXT NULL,
    "_row_index" INTEGER NOT NULL,
    "dataset" TEXT NULL,
    "source_system" TEXT NULL
);

