-- DDL Statements generated by YAML Shredder
-- Dialect: SNOWFLAKE
-- Tables: 1

-- Table: users
CREATE TABLE "users" (
    "id" NUMBER NOT NULL,
    "name" VARCHAR(10) NOT NULL,
    "age" NUMBER NOT NULL,
    "active" BOOLEAN NOT NULL
,
    PRIMARY KEY ("id")
);

